### ISSUE TITLE
@type should not be given as a list [renamed from: to_jsonld()]

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_Python#2]
I'm testing the Python package and noticed the following for "to_jsonld()":

If `@context` with `@vocab` is set the properties do not have to (should not ?) identify the vocab.
Also `@type` should not be given as a list but as a string (turning it into a list is EBRAINS KG specific and not a requirement by JSONLD).

Example for a correct openMINDS JSONLD:
``` json
{
  "@context": {
    "@vocab": "https://openminds.ebrains.eu/vocab/"
  },
  "@id": "http://localhost/openminds/instance/person/ZaphodBeeblebrox",
  "@type": "https://openminds.ebrains.eu/core/Person",
  "familyName": "Beeblebrox",
  "givenName": "Zaphod"
}
```

**Comment by apdavison** [comment]
The current implementation uses the key "vocab" in the @context, not "@vocab", so the current output is valid JSON-LD.

However, I think it's a good idea to use "@vocab"

**Comment by apdavison** [comment]
This has been separated into two issues:
- @vocab -> #11
- @type should not be a list -> this issue
