### ISSUE TITLE
Collection - detecting new linked types.

### ISSUE THREAD

**Issue by ehennestad** [openMetadataInitiative/openMINDS_Python#23]
If a user adds an instance/node to a collection, and then later adds linked types to the instance, currently that is not added to the collection. What is the best way to make sure a collection is "complete" when it is being saved.

In the openMINDS_MATLAB repo, I added a method on the collection called updateLinks. The user can invoke this, and it will also be called internally when the user saves the collection. Right now this detects if new linked types are added, but it does not detect if new linked types are removed. 

Is that a good way to solve it? It might also be possible to have an event/listener based system where if the value of linked type property is updated, the collection automatically scans through all the instances to detect changes (linked types being added or removed)

**Comment by ehennestad** [comment]
https://github.com/openMetadataInitiative/openMINDS_MATLAB/blob/f3ba6e59c32069e813253ba59dbc1b4f1b804a9b/code/%2Bopenminds/%40Collection/Collection.m#L153-L159

**Comment by apdavison** [comment]
@ehennestad I've gone with basically the same solution as you, although I've just built it directly into the `save()` method.
