### ISSUE TITLE
save() issues

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_Python#4]
I'm testing the Python package and noticed the following for "save()":

Issues with embedded types (Note: I did not set the embedded types directly, but after I created the main instance):

- Instances of embedded types with value type "array" are not correctly resolved for saving and causing an error.
- The instance of linked types in instances of embedded types are integrated as embedded not linked which is not correct (example: person -> affiliation (embedded) -> organization (linked)).
- Link to instances of linked types do not have to state their `@type` only their `@id`. Currently save adds the `@type` as well.

In the saved instance the same things hold as in issue #2 and #3.

- If `@context` with `@vocab` is set the properties do not have to (should not ?) identify the vocab. 
- `@type` should not be given as a list but as a string (turning it into a list is EBRAINS KG specific and not a requirement by JSONLD).
- Properties that require as value an array with 1 to N items always have to be defined as an array even if only one entry is provided (as defined by openMINDS).

General:

- for saving a single file (single instance or single collection file) we may want to have the extension (".jsonld") automatically added when it is not given. Or causing an error when the extension is not given. (it currently does not complain)
- saving a collection as directory should probably consider subdirectories according to schema types (instead of a purely flat list of JSONLDs)
- we may want to use UUIDs for instances instead of incremental numbers (at least as option)
- at one point in the past we decided to use this naming convention `"http://LOCALHOST/openminds/instance/SCHEMATYPE/UUID"` for `@id`s; I think something like this is better than just "_:000001"`(SCHEMATYPE would be written in lower camelCase here)

Special case:
- we may want to consider tagging instances as "sensitive" in a collection. Those instances should be stored in a separate (sub)directory than the other instances of the collection (so that they can be relocated easily into higher protected space).

**Comment by Peyman-N** [comment]
This issue was broken down to following issues 
#7 , #8 , #9 , #10 , #11 , #12 , #13 , #14 , #15 , #16

**Comment by apdavison** [comment]
Closing this, since it has been replaced with separate, more-specific issues
